name: smmart_parking_but_stupid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  lucide_icons_flutter: ^3.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logos/app/SM_2022.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/app/SM_2022.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/

  fonts:
    - family: HenrySans
      fonts:
        - asset: assets/fonts/HenrySans-Light.ttf
          weight: 300
        - asset: assets/fonts/HenrySans-Regular-2.ttf
          weight: 400
        - asset: assets/fonts/HenrySans-Medium-1.ttf
          weight: 500
        - asset: assets/fonts/HenrySans-Bold-1.ttf
          weight: 700
        - asset: assets/fonts/HenrySans-Black-4.ttf
          weight: 900
